= ownCloud Quickstart Guide
Author <bob.roldan@gmail.com>
v0.1, 2019-01-03

ifdef::env-github[]
// :imagesdir: foo/
:toc:
:toc-placement!:
endif::[]

This document provides guidance for administrators who want to install and configure
an ownCloud server and make it available to desktop and mobile clients.

For detailed instructions about deploying ownCloud, be sure to read the https://doc.owncloud.org/server/10.0/admin_manual/installation/system_requirements.html[ownCloud Server Administration Manual].

toc::[]

== Installing and configuring an ownCloud server
=== System requirements
You can install the ownCloud server on a range of Linux operating systems. Be sure that computer where you install the server meets the minimum requirements. For more information, see https://doc.owncloud.org/server/10.0/admin_manual/installation/system_requirements.html[System requirements].

=== Downloading the server ownCloud server
== Enabling connections to an ownCloud server
== Adding user accounts
== Connecting clients to an ownCloud server
Client applications are available for Microsoft Windows, Mac OS X, and Linux.
Mobile clients are available for the Android and Apple iOS operating systems.

=== Download the desktop client
=== Download the mobile client
